### PR TITLE
Add ccmod.json

### PR DESCRIPTION
**Pull request by krypciak**

### CODE REVIEW

**Comment by ZeikJT** [comment]
Does this mean I can get rid of the package.json or at least some duplicate entries? Is this the new way?

**Comment by krypciak** [comment]
Yes, you can delete `package.json` entirely.

**Comment by ZeikJT** [comment]
Nice! Feel free to do it in this PR

**Comment by ZeikJT** [comment]
Cheers!

**Comment by krypciak** [comment]
Forgot to say: A new release with the `.ccmod` it required if you want the mod to be in the database

**Comment by ZeikJT** [comment]
Ah that makes sense, I'm a bit rusty at all this as you can tell :)
Done now.

**Pull request merged**
